observe: Support -f and --first at the same time
cilium/hubble pull request #1010
Opened 2023-05-03 22:41 UTC by sladyn98

This PR removes the safeguard for support for -f and --first at the same time. This would support the following PR in the cilium repository as well to make sure the server supports it as well 

Refers to https://github.com/cilium/hubble/issues/959

2023-05-05 08:11 UTC, kaworu requested changes
Hello @sladyn98 and thanks for the PR! Couple of things:
1. Please [sign-off the commit](https://docs.cilium.io/en/stable/contributing/contributing/#developer-s-certificate-of-origin)
2. Please add tests on the way around the flags incompatibility. In particular, there should be one test case combining `--follow` and `--first` failing before the patch, and succeeding after. You can draw inspiration from [this test](https://github.com/cilium/hubble/blob/1980d391b4245b32ab1930a7c2f737dbe618652a/cmd/observe/flows_test.go#L63-L68) which setup some `selectorOpts` fields, then call `getFlowsRequest`, and finally test assumptions about the returned values.

2023-05-05 08:14 UTC, kaworu commented on cmd/observe/flows.go
> -	}
Note for reviewers: removing this check is fine, the Hubble server currently does [the same validation on the gRPC request object](https://github.com/cilium/cilium/blob/36237c2c5726b2158248554db849cfb6f8553b8e/pkg/hubble/observer/local_observer.go#L597-L602), and thus we'll still get an error if the server doesn't support combining `--first` and `--follow`.

2023-05-22 15:42 UTC, chancez commented
@sladyn98 Are you able to make the changes as requested by @kaworu ?

2023-05-22 19:26 UTC, sladyn98 commented
@chancez Yeah I am working on it

2023-08-22 15:09 UTC, chancez commented
Closing due to inactivity. Feel free to re-open if you start working on it again.

2023-08-22 15:09 UTC, closed without merging