Add filter flag documentation and examples to help message
cilium/hubble pull request #1203
Opened 2023-09-06 15:06 UTC by glrf

The Hubble CLI provides multiple different flags to filter the returned
flows. However how these filters are combined is not entirely obvious.

This commit adds more detailed help message and multiple examples that
explain how these filters interact if more than one filter flag is
provided.

I struggled to make this concise and understandable, so I added more in detailed examples. I'm happy about any input to improve this and make it clearer.

2023-09-07 14:50 UTC, chancez commented on cmd/observe/flows.go
> +    cat flows.json | hubble observe --input-file -
This is fine. We recently changed this, so the example was forgotten.

2023-09-07 14:52 UTC, chancez commented on cmd/observe/flows.go
> +  Observe provide a long list of filter options. These option let us, for example,
Fix grammar, prefer `you` over `we`.

```suggestion
  Observe provides a long list of filter options. These options let you, for example,
```

2023-09-07 14:54 UTC, chancez commented on cmd/observe/flows.go
> +  filter if it matches any of the provided values. For our example if we add a second
we -> you
```suggestion
  filter if it matches any of the provided values. For our example if you add a second
```

2023-09-07 14:54 UTC, chancez commented on cmd/observe/flows.go
> +  only flows using GET or PUT requests to endpoint in namespace 'foo' are returned.
we -> you
```suggestion
  If you add a different flag, a flow is only returned if it matches for both of the
  different flags. For example you can add a '--to-namespace' flag to our command so
  only flows using GET or PUT requests to endpoint in namespace 'foo' are returned.
```

2023-09-07 14:55 UTC, chancez commented on cmd/observe/flows.go
> +* Using reversed filters
```suggestion
* Using negations on filters
```

2023-09-07 14:55 UTC, chancez commented on cmd/observe/flows.go
> +  Similarly to filtering for multiple values, we can also filter our multiple values.
we -> you
```suggestion
  Similarly to filtering for multiple values, you can also filter our multiple values.
```

2023-09-07 14:55 UTC, chancez commented on cmd/observe/flows.go
> +  We can also filter using multiple reversed flags. This will then filter out all
We -> You
```suggestion
 You can also filter using multiple reversed flags. This will then filter out all
```

2023-09-07 14:56 UTC, chancez commented on cmd/observe/flows.go
> +the source namespace or the used protocol. To match a filter flag, a flow most
```suggestion
the source namespace or the protocol used. To match a filter flag, a flow most
```

2023-09-07 14:56 UTC, chancez commented on cmd/observe/flows.go
> +the '--not' flag in front of a filter flag. To not match a reversed filter
Reversed -> negated and remove double negative.
```suggestion
the '--not' flag in front of a filter flag. To match a negated filter
```

2023-09-07 14:57 UTC, chancez commented on cmd/observe/flows.go
> +flow does not match at least one of the reversed filter flags.
```suggestion
flow does not match any of the negated filter flags.
```

2023-09-08 07:35 UTC, glrf commented
> My only concern is this is making the already really long `--help` even longer, but I think this is fine.

That's a fair point. The help message is very long now. If this grows even more, it might be a good idea to move the examples to the docs.cilium.io and just link to them in the help message?

2023-09-08 16:00 UTC, chancez commented
@gandro @kaworu any thoughts on if we're okay with adding some more usage examples to the help test?

2023-09-11 11:16 UTC, gandro commented
> @gandro @kaworu any thoughts on if we're okay with adding some more usage examples to the help test?

Yeah, I'm also a bit worried about help page length. On the other hand, I do think those examples brings a lot of value to users who are calling `hubble observe --help` for the first time. And I think having it displayed to users when they are actively looking for help is a nice way to discover it too (since we have to assume that many people will not read or find the docs as quickly as they will try `--help`).

It's mostly users who already know the basics of Hubble for which this adds a lot of visual clutter, making it harder to quickly look up the reference for a flag they are looking for.

Maybe an option would be to maybe have short and long help flag? That I think would cover both cases: Users who are learning Hubble and want a more verbose help page, vs. users who just want to quickly know about the syntax or name of a particular flag.

2023-09-12 09:07 UTC, kaworu requested changes
Thanks @glrf! Couple of typos and nits on the way.

Overall LGTM, agree with @gandro that a short and long help would be best.

2023-09-12 13:42 UTC, glrf commented
Thanks for all the input on the help text. I often struggle with technical writing so I'm always happy about feedback.

And about the short and long help flag. I think I agree that this sounds smart, but when I actually tried to implement this I struggled to find a clean solution. I can see three ways of doing this and all three have pros and cons

* Make `-h,--help` the short help flag and introduce something like `--long-help` or `--detailed-help` or `--explain` that shows the long help text. The disadvantage here would be that new users might just not see it. Similar problem to moving it to the docs and linking.
* Make `-h,--help` the long help flag and introduce something like `-b,--brief-help` or mabye `--ref`(for reference? Or IDK naming is hard). The disadvantage here is that most people will likely just continue using `-h` and live with the clutter, as they're just used to it.
* Make `-h` show the short help text and `--help` show the long help text. I could make this work, but it felt like a hack and I don't know if that's too magical and will confuse users.

Any opinions?

2023-09-18 09:48 UTC, chancez commented
Another alternative is a new sub-command like `hubble observe usage-examples` or something?

2023-09-18 12:01 UTC, gandro approved these changes

2023-09-25 10:35 UTC, kaworu approved these changes

2023-09-25 20:49 UTC, chancez approved these changes

2023-09-26 13:08 UTC, merged