Remove Dockerfile
cilium/hubble pull request #1631
Opened 2024-12-10 15:32 UTC by michi-covalent

Hubble CLI binary already gets shipped as a part of the Cilium Agent image, so let's not maintain yet another image.

- Remove Dockerfile and build-images-release.yaml.
- Put release.yml in the release GitHub environment.

2024-12-10 15:40 UTC, Artyop approved these changes

2024-12-10 15:48 UTC, michi-covalent commented
cc @cilium/hubble-maintainers what do you think about this change 👀

2024-12-10 16:26 UTC, aanm requested changes

2024-12-10 16:26 UTC, aanm commented on .github/workflows/release.yml
> +    environment: release
Was this intentional? :thinking:

2024-12-10 17:35 UTC, glibsm approved these changes

2024-12-10 21:13 UTC, aanm approved these changes

2024-12-11 08:30 UTC, rolinh approved these changes

2024-12-11 08:30 UTC, merged