Move version into VERSION file
cilium/hubble pull request #434
Opened 2020-11-20 18:38 UTC by glibsm

Signed-off-by: Glib Smaga <code@gsmaga.com>

2020-11-20 18:50 UTC, Rolinh approved these changes

2020-11-23 09:28 UTC, Rolinh requested changes
I just realized that `RELEASE.md` needs to be updated for the change.

2020-11-23 17:33 UTC, glibsm commented
I quickly peeked into it initially but didn't see the Makefile part. I updated it, thanks.

2020-11-23 17:41 UTC, Rolinh approved these changes

2020-11-23 22:29 UTC, merged