github: Enable dependabot for stable branch
cilium/hubble pull request #849
Opened 2023-01-12 17:21 UTC by gandro

Hubble CLI currenlty maintains support for the last stable branch. To ensure security-relevant depencencies are updated, this commit introduces dependabot for the current (v0.10) stable branch with the following configuration:

  - gomod dependencies are only updated if there is a security vulnerability in one of our dependencies.
  - docker dependencies (i.e. the alpine base image)  are only updated to the next patch version
  - github actions are always updated (this mirrors cilium/cilium's configuration)

The goal of this configuration is to ensure we pull in security relevant updates, while keeping the moving parts as low as possible in the stable branch.

2023-01-13 08:21 UTC, kaworu requested changes
Thanks @gandro, all the changes make sense to me. Added a comment about `update-types` but other than that LGTM!

2023-01-13 08:21 UTC, kaworu commented on .github/dependabot.yml
> +    update-types: ["version-update:semver-patch"]
[CI is unhappy](https://github.com/cilium/hubble/pull/849/checks?check_run_id=10611332689):

```
The property '#/updates/5/' contains additional properties ["update-types"] outside of the schema when none are allowed
```

According to [the dependabot configuration doc](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#specifying-dependencies-and-versions-to-ignore) `update-types` is only supported in the `ignore:` section, so to achieve the goal of only bumping patch versions I think this should be:

```suggestion
    # Only bump the alpine patch version in stable branches
    ignore:
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
```

2023-01-16 13:23 UTC, rolinh requested changes
Thanks, lgtm except that the current stable branch is v0.11, not v0.10 :slightly_smiling_face:

2023-01-16 13:23 UTC, rolinh commented on .github/dependabot.yml
> +    target-branch: "v0.10"
```suggestion
    target-branch: "v0.11"
```

2023-01-16 13:23 UTC, rolinh commented on .github/dependabot.yml
> +    target-branch: "v0.10"
```suggestion
    target-branch: "v0.11"
```

2023-01-16 13:23 UTC, rolinh commented on .github/dependabot.yml
> +    target-branch: "v0.10"
```suggestion
    target-branch: "v0.11"
```

2023-01-16 14:14 UTC, kaworu reviewed
LGTM besides @rolinh's comment since we released `v0.11`.

2023-01-16 14:15 UTC, kaworu approved these changes

2023-01-16 14:51 UTC, gandro commented on .github/dependabot.yml
> +    target-branch: "v0.10"
:facepalm: Thanks, fixed.

2023-01-16 16:30 UTC, rolinh approved these changes

2023-01-16 17:24 UTC, merged